
CREATE TABLE CONTINENT (
  	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
	CONTINENT_CODE VARCHAR(2) NOT NULL COMMENT 'Continent Code',
  	CONTINENT_NAME VARCHAR(100) NOT NULL COMMENT 'Continent Name',
  	PRIMARY KEY (ID),
  	UNIQUE INDEX CONTINENT_UK_1 (CONTINENT_CODE, CONTINENT_NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci
COMMENT = 'World Continent''s information';

CREATE TABLE COUNTRY (
  	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  	ISO_2 VARCHAR(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2 two-letter code',
  	NAME VARCHAR(100) NOT NULL COMMENT 'Name of the Country',
  	CAPITAL VARCHAR(50) NOT NULL COMMENT 'Capital of the Country',
  	LATITUDE DECIMAL(30, 20) NOT NULL COMMENT 'Latitue information of the Country',
  	LONGITUDE DECIMAL(30, 20) NOT NULL COMMENT 'Longitude information of the Country',
  	CONTINENT_NAME VARCHAR(50) NOT NULL COMMENT 'Continent Name',
  	CURRENCY_NAME VARCHAR(50) DEFAULT NULL COMMENT 'Name of currency being used in that Country',
  	LANGUAGE TEXT DEFAULT NULL COMMENT 'Official Languages of that Country',
  	PRIMARY KEY (ID),
  	UNIQUE INDEX COUNTRY_UK_1 (ISO_2, NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci
COMMENT = 'Countries information';
